import { Component, OnInit } from '@angular/core';
import { LoginStatusService } from 'src/app/shared/login-status.service';
import { LoginService } from '../login-signup/login/login.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-my-bookings',
  templateUrl: './my-bookings.component.html',
  styleUrls: ['./my-bookings.component.css']
})
export class MyBookingsComponent implements OnInit {

  myBookings : Array<any> = [];

  AUTH_TOKEN = "";

  constructor(private loginStatus : LoginStatusService, private loginService : LoginService,
              private  router :Router ) {
    this.AUTH_TOKEN = this.loginService.getAuthToken();

    this.loginStatus.verifyAuthToken(this.AUTH_TOKEN).subscribe(
      ( data : any ) => {
               
        if (data.code == "0") {
          console.log(data);
        }
        else {
          // router.navigate(['']);
        }
      }      
    );

    this.myBookings =   [
      {
          "booking": {
              "bookingId": "Visa1567752440113YALkjxvMckqu",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-06",
              "paymentId": "Visa1567752519826fn2HxoRnwOUU",
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Payment completed"
          },
          "travellers": [
              {
                  "emailId": "bawa@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567751043869qTpCRYbVZQgN",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-06",
              "paymentId": "Visa1567751089078kCxvlPGDnIEo",
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Payment initiated"
          },
          "travellers": [
              {
                  "emailId": "bawa@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567750147989VdYLyiU2zalo",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-06",
              "paymentId": "Visa1567750658880GFeAbGNszeY3",
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Payment initiated"
          },
          "travellers": [
              {
                  "emailId": "bawa@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567749874031UhyehiruZPJP",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-06",
              "paymentId": "Visa1567749918398FGM39y3cD078",
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Payment completed"
          },
          "travellers": [
              {
                  "emailId": "bawa@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment completed",
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567745888175j5VNM5k7c1SV",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-06",
              "paymentId": "Visa1567746885066yKQV7gPLz3jo",
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Payment initiated"
          },
          "travellers": [
              {
                  "emailId": "bawa@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment initiated",
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment initiated",
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567744792675Pmupztkl5Nbv",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-06",
              "paymentId": "Visa1567744810666zD8Q2R7YT6DJ",
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Payment inaitiated"
          },
          "travellers": [
              {
                  "emailId": "bawa@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment inaitiated",
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": "Payment inaitiated",
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567743464166DijkZfi310Nl",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-06",
              "paymentId": null,
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Visa application filled"
          },
          "travellers": [
              {
                  "emailId": "bawa@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567691361840N5E8Gb0xyZSb",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-05",
              "paymentId": null,
              "gstNumber": "asbdjhsavd",
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Visa application filled"
          },
          "travellers": [
              {
                  "emailId": "dhruv@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567690438072yxrDOGY3YJfo",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-05",
              "paymentId": null,
              "gstNumber": null,
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Visa application filled"
          },
          "travellers": [
              {
                  "emailId": "dhruv@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa15676902056418zglv3FoucAT",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-05",
              "paymentId": null,
              "gstNumber": null,
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Visa application filled"
          },
          "travellers": [
              {
                  "emailId": "dhruv@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa15676901463769OhHtVylg11q",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-05",
              "paymentId": null,
              "gstNumber": null,
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Visa application filled"
          },
          "travellers": [
              {
                  "emailId": "dhruv@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567497465429CSthu7YX4S3g",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-03",
              "paymentId": null,
              "gstNumber": null,
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Visa application filled"
          },
          "travellers": [
              {
                  "emailId": "dhruv@visa2fly.com",
                  "firstName": "Dhruv",
                  "middleName": "Kumar",
                  "lastName": "Kadyan",
                  "cellNumber": "9810019581",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              },
              {
                  "emailId": "sumedh@visa2fly.com",
                  "firstName": "Sumedh",
                  "middleName": null,
                  "lastName": "gupta",
                  "cellNumber": "9810017687",
                  "code": "+91",
                  "addressLine1": null,
                  "addressLine2": null,
                  "city": "Delhi",
                  "state": "New Delhi",
                  "pinCode": "110047",
                  "title": "Mr",
                  "passportNumber": null,
                  "passportExpiryDate": "2020-12-01",
                  "passportFrontUrl": null,
                  "passportBioImage": null,
                  "userImageUrl": null,
                  "departureFlightTicketUrl": null,
                  "arrivalFlightTicketUrl": null,
                  "hotelAccommodationUrl": null,
                  "sixMonthsBankStatementUrl": null,
                  "insuranceUrl": null,
                  "bookingStatus": null,
                  "onlineCountry": false,
                  "country": "India"
              }
          ]
      },
      {
          "booking": {
              "bookingId": "Visa1567495978869cYz4q1pyeamC",
              "documentCollectionDate": "2019-10-01",
              "dateOfTravel": "2019-10-28",
              "totalTravellers": 2,
              "bookingDate": "2019-09-03",
              "paymentId": null,
              "gstNumber": null,
              "bookingType": "Visa",
              "visaForCountry": "Thailand",
              "visaType": "TOURIST",
              "entryType": "MULTIPLE ENTRY",
              "bookingStatus": "Visa application filled"
          },
          "travellers": []
      }
  ]

   }

  ngOnInit() {
  }

}
